"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ChevronRight } from "lucide-react";
import { useTranslation } from "react-i18next";
import { AppShell } from "@/components/tsq/app-shell";
import { tsqApi } from "@/lib/tsq/api";

export default function RelationshipSettingsPage({ params }: { params: Promise<{ threadId: string }> }) {
  const { t } = useTranslation(); const [threadId, setThreadId] = useState(""); const [draft, setDraft] = useState({ muted: false, blocked: false }); const [saving, setSaving] = useState(false); const [blockConfirm, setBlockConfirm] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { params.then(async ({ threadId: id }) => { setThreadId(id); setDraft(await tsqApi.getRelationshipSettings(id)); }).catch(() => setNotice(t("tsq.chat.retry"))); }, [params, t]);
  async function save(next: typeof draft) { if (!threadId || saving) return; setSaving(true); setNotice(""); try { setDraft(await tsqApi.updateRelationshipSettings(threadId, next)); setNotice(t("tsq.chat.saved")); } catch { setNotice(t("tsq.chat.retry")); } finally { setSaving(false); } }
  return <AppShell><header className="flex min-h-16 items-center gap-3 border-b border-[color:var(--border)] px-4"><Link href={`/messages/${threadId}`} aria-label={t("tsq.chat.back")} className="grid h-11 w-11 place-items-center rounded-full bg-white"><ArrowLeft className="h-5 w-5" /></Link><h1 className="text-lg font-bold">{t("tsq.chat.relationshipSettings")}</h1></header><main className="space-y-3 p-4"><Setting label={t("tsq.chat.mute")} pressed={draft.muted} disabled={saving} onClick={() => save({ ...draft, muted: !draft.muted })} /><Setting label={t("tsq.chat.block")} pressed={draft.blocked} disabled={saving} onClick={() => setBlockConfirm(true)} /><Link href={`/messages/${threadId}/report`} className="flex min-h-14 items-center justify-between rounded-2xl bg-white px-4 text-sm text-destructive shadow-[var(--brand-shadow-sm)]">{t("tsq.chat.report")}<ChevronRight className="h-4 w-4" /></Link>{notice && <p className="text-center text-sm text-muted-foreground">{notice}</p>}</main>{blockConfirm && <div className="fixed inset-0 z-30 grid place-items-end bg-black/45 p-4"><div className="w-full rounded-3xl bg-[color:var(--bg-canvas)] p-5"><h2 className="text-lg font-bold">{t("tsq.chat.blockConfirm")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("tsq.chat.blockConfirmBody")}</p><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => setBlockConfirm(false)} className="min-h-11 rounded-full bg-white text-sm">{t("tsq.chat.keepChatting")}</button><button onClick={() => { setBlockConfirm(false); save({ ...draft, blocked: true }); }} className="min-h-11 rounded-full bg-destructive text-sm text-white">{t("tsq.chat.blockConfirm")}</button></div></div></div>}</AppShell>;
}
function Setting({ label, pressed, disabled, onClick }: { label: string; pressed: boolean; disabled: boolean; onClick: () => void }) { return <button aria-pressed={pressed} disabled={disabled} onClick={onClick} className="flex min-h-14 w-full items-center justify-between rounded-2xl bg-white px-4 text-left text-sm shadow-[var(--brand-shadow-sm)]"><span>{label}</span><span className={`h-6 w-11 rounded-full p-1 ${pressed ? "bg-[color:var(--primary)]" : "bg-neutral-200"}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${pressed ? "translate-x-5" : ""}`} /></span></button>; }
