"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ImagePlus } from "lucide-react";
import { useTranslation } from "react-i18next";
import { AppShell } from "@/components/tsq/app-shell";
import { tsqApi, type ReportReason } from "@/lib/tsq/api";

const reasons: ReportReason[] = ["harassment", "fraud", "unsafe", "illegal", "other"];
export default function ReportPage({ params }: { params: Promise<{ threadId: string }> }) {
  const { t } = useTranslation(); const [selected, setSelected] = useState<ReportReason[]>([]); const [description, setDescription] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [receipt, setReceipt] = useState("");
  async function submit() { const threadId = (await params).threadId; if (reasons.length === 0 || selected.length === 0) { setError(t("tsq.report.validation")); return; } setPending(true); setError(""); try { const result = await tsqApi.submitConversationReport({ threadId, reasons: selected, description }); setReceipt(result.reportId); } catch { setError(t("tsq.report.retry")); } finally { setPending(false); } }
  return <AppShell><header className="flex min-h-16 items-center gap-3 border-b border-[color:var(--border)] px-4"><Link href="/messages" aria-label={t("tsq.chat.back")} className="grid h-11 w-11 place-items-center rounded-full bg-white"><ArrowLeft className="h-5 w-5" /></Link><h1 className="text-lg font-bold">{t("tsq.report.title")}</h1></header><main className="space-y-5 p-4">{receipt ? <section className="rounded-3xl bg-white p-6 text-center shadow-[var(--brand-shadow-sm)]"><h2 className="text-lg font-bold">{t("tsq.report.submitted")}</h2><p className="mt-2 text-sm text-muted-foreground">{t("tsq.report.submittedHint")}</p><p className="mt-2 text-xs text-muted-foreground">{receipt}</p><Link href="/messages" className="mt-5 inline-flex min-h-11 items-center rounded-full bg-[color:var(--primary)] px-5 text-sm text-white">{t("tsq.report.backToChat")}</Link></section> : <><p className="text-sm text-muted-foreground">{t("tsq.report.subtitle")}</p><div className="grid gap-2">{reasons.map((reason) => <button key={reason} aria-pressed={selected.includes(reason)} onClick={() => setSelected((current) => current.includes(reason) ? current.filter((item) => item !== reason) : [...current, reason])} className={`min-h-12 rounded-2xl border px-4 text-left text-sm ${selected.includes(reason) ? "border-[color:var(--primary)] bg-[color:var(--soft)]" : "border-[color:var(--border)] bg-white"}`}>{t(`tsq.report.${reason}`)}</button>)}</div><label className="block text-sm font-medium">{t("tsq.report.description")}<textarea value={description} onChange={(event) => setDescription(event.target.value)} className="mt-2 min-h-28 w-full rounded-2xl border border-[color:var(--border)] bg-white p-3 text-sm" /></label><div className="flex min-h-16 items-center gap-2 rounded-2xl bg-white px-4 text-sm text-muted-foreground"><ImagePlus className="h-5 w-5" />{t("tsq.report.evidenceUnavailable")}</div>{error && <p className="text-sm text-destructive">{error}</p>}<button disabled={pending} onClick={submit} className="min-h-12 w-full rounded-full bg-[color:var(--primary)] text-sm text-white disabled:opacity-50">{pending ? t("tsq.report.submitting") : t("tsq.report.submit")}</button></>}</main></AppShell>;
}
