import type { MyPost } from "@/stores/profile-store";

export const DEFAULT_MY_POSTS: MyPost[] = [
  {
    id: "seed-1",
    intent: "have",
    channelKey: "share-exp",
    channelLabel: "经验",
    kind: "green",
    emoji: "🎯",
    title: "转行做 UI 设计，我踩过的 5 个坑",
    text: "我这里可以分享从零基础转行到入职一年期间踩过的坑，包括作品集、面试准备、谈薪和试用期适应。适合正在考虑转行、需要真实经验参考的朋友。",
    images: ["/channel/e1.png"],
    place: "我发布 · 我拥有",
    time: "2 小时前",
    likes: 132,
    favorites: 88,
    status: "published",
    completedCount: 0,
    discoveryVisible: true,
    publicDisplay: true,
    comments: [
      { id: "c1", author: "野生设计师", emoji: "🎨", text: "作品集已私信，期待合作！", time: "昨天", likes: 0 },
    ],
  },
  {
    id: "seed-2",
    intent: "want",
    channelKey: "find-people",
    channelLabel: "合作伙伴",
    kind: "purple",
    emoji: "🎨",
    title: "寻找品牌设计师，长期合作共创项目",
    text: "我想寻找一位有想法、有审美的品牌设计师，长期合作，按项目结算，也接受资源互换。",
    images: ["/discover/p3.png"],
    place: "我发布 · 我想要",
    time: "昨天",
    likes: 78,
    favorites: 31,
    status: "published",
    completedCount: 1,
    needsPostResolution: true,
    discoveryVisible: true,
    publicDisplay: true,
    comments: [
      { id: "c1", author: "野生设计师", emoji: "🎨", text: "作品集已私信，期待合作！", time: "昨天", likes: 0 },
      { id: "c2", author: "林一叶", emoji: "🌿", text: "我可以帮忙介绍一位品牌朋友。", time: "昨天", likes: 0 },
    ],
  },
  {
    id: "seed-3",
    intent: "have",
    channelKey: "give-idle",
    channelLabel: "闲置",
    kind: "warm",
    emoji: "📷",
    title: "闲置相机包转让，可同城自提",
    text: "我这里有一个闲置相机包，成色不错，适合同城自提。桥约已完成一次，但可以作为成果继续展示。",
    images: ["/channel/i2.png"],
    place: "我发布 · 我拥有",
    time: "3 天前",
    likes: 26,
    favorites: 9,
    status: "completed",
    completedCount: 1,
    discoveryVisible: true,
    publicDisplay: true,
    comments: [],
  },
  {
    id: "seed-4",
    intent: "have",
    channelKey: "share-exp",
    channelLabel: "经验",
    kind: "green",
    emoji: "🍙",
    title: "周末一起整理城市美食地图",
    text: "我想把自己收藏的同城小店整理成地图，也欢迎朋友一起补充真实体验。这个帖子当前仅自己可见。",
    images: ["/channel/t2.png"],
    place: "我发布 · 我拥有",
    time: "上周",
    likes: 12,
    favorites: 4,
    status: "completed",
    completedCount: 1,
    discoveryVisible: false,
    publicDisplay: false,
    comments: [],
  },
];
